[settings]
lockfile = true
experimental = true

[tools]
"npm:turbo" = "latest"
opencode = "latest"
yarn = "latest"
bun = "latest"
node = "lts/krypton"
"npm:ocx" = "latest"

[env]
OC_PORT = 49829
OCX_PROFILE = "rie-ws"
