export const CHART_COLORS = {
  fire: "hsl(var(--destructive))",
  flood: "hsl(var(--primary))",
  crime: "hsl(var(--accent))",
  medical: "hsl(142 71% 45%)",
  infrastructure: "hsl(270 75% 65%)",
  weather: "hsl(199 98% 58%)",
  primary: "hsl(var(--primary))",
  accent: "hsl(var(--accent))",
  muted: "hsl(var(--muted))",
  border: "hsl(var(--border))",
  foreground: "hsl(var(--foreground))",
  card: "hsl(var(--card))",
  cardForeground: "hsl(var(--card-foreground))",
  secondary: "hsl(var(--secondary))",
  success: "hsl(142 71% 45%)",
  warning: "hsl(45 94% 50%)",
  chart: {
    1: "hsl(var(--primary))",
    2: "hsl(var(--accent))",
    3: "hsl(270 75% 65%)",
    4: "hsl(142 71% 45%)",
    5: "hsl(45 94% 50%)",
    6: "hsl(199 98% 58%)",
  },
}
