import type { ChartBlock } from "./dashboard-blocks"

export const DEFAULT_BLOCKS: Array<Omit<ChartBlock, "id">> = [
  {
    type: "stat-card",
    title: "Total Incidents",
    subtitle: "Last 30 days",
    dataKey: "metrics",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    type: "stat-card",
    title: "Active Response",
    subtitle: "Currently deployed",
    dataKey: "metrics",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    type: "stat-card",
    title: "Avg Response Time",
    subtitle: "Minutes",
    dataKey: "metrics",
    colSpan: 1,
    rowSpan: 1,
    unit: "min",
  },
  {
    type: "stat-card",
    title: "Resolution Rate",
    subtitle: "Last 30 days",
    dataKey: "metrics",
    colSpan: 1,
    rowSpan: 1,
    unit: "%",
  },
  {
    type: "line",
    title: "Incident Trends",
    subtitle: "By type over time",
    dataKey: "trends",
    colSpan: 3,
    rowSpan: 1,
  },
  {
    type: "area",
    title: "Response Time Trend",
    subtitle: "Avg vs P90 by day",
    dataKey: "trends",
    colSpan: 2,
    rowSpan: 1,
  },
  {
    type: "bar",
    title: "Incidents by Zone",
    subtitle: "Barangay breakdown",
    dataKey: "incidents",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    type: "composed",
    title: "Resource Utilization",
    subtitle: "Teams vs incidents",
    dataKey: "trends",
    colSpan: 2,
    rowSpan: 2,
  },
  {
    type: "radar",
    title: "District Risk Profile",
    subtitle: "6 dimensions",
    dataKey: "districts",
    colSpan: 1,
    rowSpan: 2,
  },
  {
    type: "pie",
    title: "Severity Distribution",
    subtitle: "By severity level",
    dataKey: "incidents",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    type: "radial",
    title: "Resolution Rate",
    subtitle: "By incident type",
    dataKey: "incidents",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    type: "scatter",
    title: "Zone Risk Matrix",
    subtitle: "Population vs incidents",
    dataKey: "zones",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    type: "gauge-arc",
    title: "Current Load",
    subtitle: "System capacity",
    dataKey: "metrics",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    type: "wind-rose",
    title: "Wind Direction",
    subtitle: "Incident origins",
    dataKey: "directions",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    type: "compass",
    title: "Compass Heading",
    subtitle: "Current direction",
    dataKey: "directions",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    type: "spark-bar",
    title: "Severity Spark",
    subtitle: "Quick view",
    dataKey: "incidents",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    type: "timeline-heatmap",
    title: "Activity Timeline",
    subtitle: "Last 30 days",
    dataKey: "heatmap",
    colSpan: 2,
    rowSpan: 1,
  },
  {
    type: "calendar-heat",
    title: "Calendar Heatmap",
    subtitle: "Full year view",
    dataKey: "calendar",
    colSpan: 2,
    rowSpan: 1,
  },
  {
    type: "bullet",
    title: "SLA Performance",
    subtitle: "Response time targets",
    dataKey: "bulletMetrics",
    colSpan: 2,
    rowSpan: 1,
  },
]
